# this is the name of our action.
# this will be displayed in 'Actions' tab on your repo's github page when running.
name: deploy staging

# the trigger for the action.
# we are interested only in pushes onto a 'dev' branch
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
    
# jobs to be done.
# each job has multiple steps.
# jobs can depend on other jobs, but in out case it's very linear.
jobs:
  build:
    # name of the job (you will see this in Actions view on Github)
    name: build and deploy of staging
    # part of specification what kind of remote machine should Action use to execute the jobs on
    runs-on: ubuntu-22.04
    # steps are what you see in logs in Actions
    steps:
    # we use an action that somebody previously made that allows to get the latest version of the code from the specific branch
#     - name: checkout 'dev'
#       uses: actions/checkout@master
#       with:
#         ref: build

    # we also use previously made action that enables us to copy fies from a remote machine that Action is using currently, to another machine, via SSH
    - name: copy the files
      uses: appleboy/scp-action@master
      with:
        run: seven@192.168.2
        run: seven
#         host: 192.168.0.2
#         username: usernginx
#         password: seven
#         source: "."
#         target: "/var/www/192.168.0.2"

#     # clean build of frontend
#     - name: build clean frontend
#       uses: appleboy/ssh-action@master
#       with:
#         host: 192.168.0.2
#         username: seven
#         password: seven
#         script: |
#           cd /var/www/192.168.0.2
#           npm
#           npm run build
