# this is the name of our action.
# this will be displayed in 'Actions' tab on your repo's github page when running.
name: deploy staging

# the trigger for the action.
# we are interested only in pushes onto a 'dev' branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# jobs to be done.
# each job has multiple steps.
# jobs can depend on other jobs, but in out case it's very linear.
jobs:
  build:
    # name of the job (you will see this in Actions view on Github)
    name: build and deploy of staging
    # part of specification what kind of remote machine should Action use to execute the jobs on
    runs-on: ubuntu-22.04
    # steps are what you see in logs in Actions
    steps:
    # we use an action that somebody previously made that allows to get the latest version of the code from the specific branch
#     - name: checkout 'dev'
#       uses: actions/checkout@master
#       with:
#         ref: build

    # we also use previously made action that enables us to copy fies from a remote machine that Action is using currently, to another machine, via SSH
    - name: copy the files
      uses: appleboy/scp-action@master
      with:
        host: 192.168.0.2
        username: seven
        port: 21
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        source: "."
        target: "/var/www/192.168.0.2"

    # clean build of frontend
    - name: build clean frontend
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.0.2
        username: seven
        port: 21
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        script: |
          cd /var/www/192.168.0.2
          npm
          npm run build

#     # clean build of backend
#     - name: build clean backend
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST_PRODUCTION }}
#         username: ${{ secrets.USERNAME_STAGING }}
#         port: ${{ secrets.PORT_STAGING }}
#         key: ${{ secrets.SSH_KEY_STAGING }}
#         script: |
#           cd /var/www/__APP__/server
#           yarn
#           yarn build
#           pm2 restart all

#     # we don't even build our API server, but simple tell pm2 to run it.
#     # we communicate with our staging hosting server via SSH using an action previously made.
#     - name: restart pm2 for backend
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST_STAGING }}
#         username: ${{ secrets.USERNAME_STAGING }}
#         port: ${{ secrets.PORT_STAGING }}
#         key: ${{ secrets.SSH_KEY_STAGING }}
#         script: |
#           pm2 stop all
#           pm2 delete all
#           pm2 start /var/www/__APP__/server/index.js --name tourbillon-staging
